### ISSUE TITLE
cleanmgr vs dism

### ISSUE THREAD

**Issue by havealoha** [TheVDIGuys/W10_1803_VDI_Optimize#2]
There is some overlap between the advice here https://techzone.vmware.com/creating-optimized-windows-image-vmware-horizon-virtual-desktop , the tool here https://labs.vmware.com/flings/vmware-os-optimization-tool ,  and the script you have created here on github.

I understand the this is Microsoft vs VMware practice. However, can you justify the absence of "dism /online /cleanup-image /startcomponentcleanup /resetbase" or "sdelete64 -z c:" in the script. Can you justify one way or the other?

**Comment by tmmuessig** [comment]
We have consulted with the Servicing team and looked at our current official documentation.
 
Up until now we have relied on the Disk Cleanup Wizard (DCW), with the “Windows Update Cleanup” option. DCW has done a great job of cleaning up, but is now deprecated. The DISM command is a good option. In the next version of the cleanup script we are going to consider using the DISM command, or the built-in scheduled task called “StartComponentCleanup”, which can be run from command line, and is documented in this article:
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/clean-up-the-winsxs-folder

Running the SDELETE.exe utility is a good idea. We may incorporate that into a future version of the script.
